# Generated by Django 3.2.7 on 2021-10-01 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20211001_1140"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="invitation",
            unique_together={("company", "user")},
        ),
    ]
