# Generated by Django 3.2.7 on 2021-09-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertask",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "proposed"), (2, "confirmed"), (3, "rejected")], default=1
            ),
        ),
    ]
