# Generated by Django 3.2.7 on 2021-12-21 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_auto_20211117_0955"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worktime",
            name="start_time",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
