# Generated by Django 3.2.7 on 2021-12-21 16:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_alter_worktime_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worktime",
            name="start_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
