# Generated by Django 3.2.7 on 2022-01-03 10:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_alter_worktime_start_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="worktime",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
